### ISSUE TITLE
Season 2 Additions

### ISSUE THREAD

**Issue by Telnaior** [Telnaior/RtaB-Bot#23]
Super Bot Challenge side mode, allowing players to bet on the bots

**Comment by StrangerCoug** [comment]
A couple I thought of some time ago:

**Robin Hood:** steal all cash from the player who has the most cash (if tied, then make it so you don't "steal" from yourself; if still tied, then steal from the highest-ranked player). However, if you are the richest player and not in a tie with anyone, the poorest player steals all **YOUR** cash instead! (Ties for the poorest player break in favor of the lowest-ranked one.) I haven't given full consideration as to what happens when the richest player does not have a positive total; I'm willing to entertain discussion here.

**Yoink** (I think you had this in your Skype version): You are "eliminated" _per se_ and lose your streak bonus accordingly, but you don't incur an elimination penalty to your score and you get to keep your booster.

**Shut the Box:** Minigame (that I've already started work on) with 12 numbers in the box; each number successfully closed is $25,000 × the number rolled, but if you get a bad roll, you lose everything.

(Plus some other minigames involving cards and dice: I'd love to see them!)

**Comment by Gizensha** [comment]
I'm Stephen on the discord.

Concept addition: 

**Microgames**. Like minigames, but much quicker to run - All inputs should be handled by one line, and outputs to a single line or box, similar to Blammo. Played when you grab them (so should be balanced to give about as much cash as a cash space) and impacted by booster but not win bonus. If implemented, consider reworking Math Time to be one.

Possible microgame that was discussed in the discord (in the context of a minigame with a bit of a more involved bonus and for more cash) - The wheel from Price is Right. It picks a number from between 5 and 100, you pick if to spin again. If you go over 100 you bust. Get 1000 times your spin, or 200k if you get an exact 100.

**Cash Dice** - Minigame (Could likely be simplified to work as a microgame, if those are added) - Basically yahtzee, without the chance space. Roll five dice. Keep as many as you want, reroll the rest up to two times.  Win an amount of cash based on what you'd score in Yahtzee (which tops out at 50, so 10,000x would see a 500k top prize, with around 50k guaranteed if we allow top row spaces to be used)

**Comment by Telnaior** [comment]
Pretty much everything I'm going to implement from here for S2 is more or less done, already got quite a number of new events and mostly looking for another couple of new minigames now.
To clarify: Anything removed from the comments got implemented as written. Super Bot Challenge is done but won't have betting (yet). Waiting on Shut the Box from SC, other events are interesting but I'll likely hold off until S3 on implementing them (S3 is when I'm gonna look at more persistent / progressive elements).
Microgames are kind of interesting but I'm not entirely sure of the value of them considering they're basically glorified cash spaces (seems like something that might be better suited to a forum game?).
Cash Dice would be cool, but probably makes more sense as 20,000x without an upper section or chance for the top prize of 1m (and it's waiting on Shut the Box for the dice object in any case).
Other than that, I feel like we're getting close enough to the end of S1 that it seems sensible to leave other S2 stuff off to the side for a bit so that we don't get new things coming in during the initial bugfix rush. Thanks for the help, everyone!
